SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT i.ID, n.FISH_NAME, i.LENGTH,
    ROW_NUMBER() OVER (PARTITION BY i.FISH_TYPE ORDER BY i.LENGTH DESC) AS rn
    FROM FISH_INFO i
    JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE    
) t
WHERE rn = 1
ORDER BY ID;