SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
WHERE (i.FISH_TYPE, i.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID;

/*
FISH_INFO : 잡은 물고기들의 정보
ID, FISH_TYPE, LENGTH, TIME
10cm 이하면 LENGTH = NULL

FISH_NAME_INFO : 물고기의 이름에 대한 정보
FISH_TYPE, FISH_NAME

1.물고기 종류 별로 가장 큰 물고기의 ID, 물고기의 이름, 길이를 출력하는 SQL
2.컬럼명 조건 ID, FISH_NAME, LENGTH
3.물고기 ID에 대해 오름차순 정렬. order by asc
*/